# Generated by Django 5.0.6 on 2024-06-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_task_id_task_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='task_id',
        ),
    ]
