# Generated by Django 5.0.6 on 2024-06-18 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.notification')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.report')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.task')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReportEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.eventlog')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.forecast')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.notification')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dashboard.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.report')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.weather')),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
