# Generated by Django 5.0.6 on 2024-06-20 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_groups_userprofile_user_permissions_and_more'),
        ('reports', '0002_alter_reportdetail_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
