# Generated by Django 5.0.6 on 2024-06-21 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_groups_and_more'),
        ('dashboard', '0004_alter_eventlog_task_alter_eventlog_user_and_more'),
        ('reports', '0004_alter_userreport_report_alter_userreport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.report'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
