# Generated by Django 5.0.6 on 2024-06-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_task_created_at_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_id',
            new_name='task',
        ),
    ]
