# Generated by Django 5.0.6 on 2024-07-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_category_user_alter_eventlog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default='2023-12-12 00:00'),
            preserve_default=False,
        ),
    ]
