# Generated by Django 5.0.6 on 2024-07-02 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_task_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
    ]
