# Generated by Django 5.0.6 on 2024-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_manually_completed',
            field=models.BooleanField(default=False),
        ),
    ]
