# Generated by Django 5.0.6 on 2024-06-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
