# Generated by Django 5.0.6 on 2024-06-21 10:33

import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskcategory_taskforecast_taskreport_taskweather_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrelationship',
            name='user',
            field=models.ForeignKey(default=tasks.models.get_default_username, on_delete=django.db.models.deletion.CASCADE, related_name='task_relationships', to=settings.AUTH_USER_MODEL),
        ),
    ]
