# Generated by Django 5.0.6 on 2024-06-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_reportdetail_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdetail',
            name='user_profile',
        ),
    ]
