# Generated by Django 5.0.6 on 2024-06-20 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0002_currentweather_weatherforecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
