# Generated by Django 5.0.6 on 2024-06-21 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_eventlog_user_alter_forecast_user_and_more'),
        ('tasks', '0003_alter_usertask_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskforecast',
            name='forecast',
        ),
        migrations.RemoveField(
            model_name='taskforecast',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskreport',
            name='report',
        ),
        migrations.RemoveField(
            model_name='taskreport',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskweather',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskweather',
            name='weather',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='event_log',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='air_pressure',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='uv_index',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='wind_direction',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='wind_speed',
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='air_pressure',
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='uv_index',
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='wind_speed',
        ),
        migrations.CreateModel(
            name='TaskRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboard.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
                ('event_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboard.eventlog')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboard.forecast')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboard.report')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_relationship', to='dashboard.task')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboard.weather')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskCategory',
        ),
        migrations.DeleteModel(
            name='TaskForecast',
        ),
        migrations.DeleteModel(
            name='TaskReport',
        ),
        migrations.DeleteModel(
            name='TaskWeather',
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
