# Generated by Django 5.0.6 on 2024-06-21 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_eventlog_user_alter_forecast_user_and_more'),
        ('tasks', '0004_remove_taskforecast_forecast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.forecast')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.report')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.task')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.weather')),
            ],
        ),
        migrations.DeleteModel(
            name='CurrentWeather',
        ),
        migrations.DeleteModel(
            name='WeatherForecast',
        ),
        migrations.RemoveField(
            model_name='taskrelationship',
            name='category',
        ),
        migrations.RemoveField(
            model_name='taskrelationship',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='taskrelationship',
            name='forecast',
        ),
        migrations.RemoveField(
            model_name='taskrelationship',
            name='report',
        ),
        migrations.RemoveField(
            model_name='taskrelationship',
            name='weather',
        ),
        migrations.AlterField(
            model_name='taskrelationship',
            name='event_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.eventlog'),
        ),
        migrations.AlterField(
            model_name='taskrelationship',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.task'),
        ),
    ]
